### ISSUE TITLE
plugin-holder overlaps navigation

### ISSUE THREAD

**Issue by marcelhadorn** [darklow/django-suit#159]
Add this to the suit.css to prevent plugin-holders to overlap the navigation on the right:

``` CSS
body.cms-page .form-horizontal fieldset.plugin-holder, body.cms-page .plugin-holder-separator:last-of-type { margin-left:0px !important;}
```
