### ISSUE TITLE
Problemas with DjangoCms 3

### ISSUE THREAD

**Issue by SalahAdDin** [darklow/django-suit#330]
Hi guys,no i'm using django cms,the latest version, but, i have some problems with it.
![cms error uno](https://cloud.githubusercontent.com/assets/5034215/5506428/1f0f009c-8768-11e4-95b1-55cb877cddbe.png)
This is the fist, the admin for pages are very bad,isn't django suit theme, is some one like django cms admin.

![cms error uno](https://cloud.githubusercontent.com/assets/5034215/5506493/daff739a-8768-11e4-9598-4d94473d2306.png)
And them, when i want edit the page i find this, the django cms edit page, not your django suit edit page.

You can show me how do you configure django cms for your demo?

You can see here many other problemas with cms, in this cases, permisions template error:
![captura de pantalla de 2014-12-19 10 27 51](https://cloud.githubusercontent.com/assets/5034215/5506628/017dbcf6-876a-11e4-97ae-38a034480b40.png)

Thank you very much.

**Comment by ad-lebedev** [comment]
Hi! I'll try to fix some of this problems with adding of custom css file to the base_site.html template.
This is the first part:
```css
.change-list .filtered {
	background: inherit !important; 
}

#changelist #sitemap {
	box-shadow: 0 0 1px rgba(0, 0, 0, 0.4);
	border-bottom-right-radius: 0;
  	border-bottom-left-radius: 0;
  	border-top-left-radius: 4px;
  	border-top-right-radius: 4px;
	border: none;
	background: none;
}

#changelist #sitemap ul.header {
	margin: 0;
	padding: 0;
  	height: auto;
  	background-clip: padding-box;
  	border-top-left-radius: 4px;
  	border-top-right-radius: 4px;
  	border-bottom-left-radius: 0;
	border-bottom-right-radius: 0;
}

#changelist #sitemap ul.header li {
	margin: 0;
  	display: block;
  	color: #333333;
  	text-shadow: 0 1px rgba(255, 255, 255, 0.5);
  	font-weight: bold;
  	background-color: #e5e5e5;
	background-repeat: no-repeat;
	background-image: -webkit-linear-gradient(#f3f3f3, #e5e5e5);
	background: transparent;
	background-image: -webkit-linear-gradient(#f3f3f3, #e5e5e5) !important;
	background-position-x: initial;
	background-position-y: initial;
	background-size: initial;
	background-repeat-x: no-repeat;
	background-repeat-y: no-repeat;
	background-attachment: initial;
	background-origin: initial;
	background-clip: padding-box !important;
	background-color: #e5e5e5 !important;
}

#changelist #sitemap ul.header li .cont {
	display: block;
	border: 0;
	white-space: nowrap;
	height: auto;
	box-shadow: inset 1px 1px 0 rgba(255, 255, 255, 0.3);
	text-shadow: 0 1px rgba(255, 255, 255, 0.5);
}

.tree-default li .cont {
	background: #fff;
	border-color: #e5e5e5;
	box-shadow: inset 1px 1px 0 #ffffff;
	text-shadow: 0 1px rgba(255, 255, 255, 0.5);
}

#sitemap li a.addlink, #sitemap li a.deletelink {
	width: 18px;
	height: 18px;
	margin-left: 0;
	background: url("../img/pagetree/sprite.png") no-repeat 0 0;
	background-position: -40px 0;
}

#sitemap li a.deletelink {
	background-position: -40px -40px;
}
```
if you need, I'll update this thread with new changes as soon as I'll test it.

**Comment by SalahAdDin** [comment]
So late, now i'm using wagtail, but, thank you!.

**Comment by ad-lebedev** [comment]
Ok, I'll just leave it here ;)
One more thing to fix layout:
``` css
#sitemap .moveable {
	z-index: inherit;
}
```
