### ISSUE TITLE
More consistent presentation of search fields

### ISSUE THREAD

**Issue by skndn60** [darklow/django-suit#55]
To improve the end user experience, add a more meaningful placeholder value in the search fields. At the moment it's anybody's guess on what attributes a search is actually performed. I think this is a standard Django short coming as, if I remember correctly, the standard admin doesn't show any placeholder values either.

**Comment by vkorichkov** [comment]
Overwrite **search_form.html**:

```python
....
{% load i18n admin_static suit_list admin_list suit_tags cs_tags %}
....

<div style="display:inline;" class="couponcode">  <!-- !!! class="couponcode" -->
                <input type="text" size="40" name="{{ search_var }}" ....
<span class="coupontooltip">
                        <b>Search in:</b><br/>
                        &nbsp;<b><i>Column (type of search)</i></b><br/>
                        {% for field in cl.search_fields %}
                                {% if field|slice:':1' == '=' %}
                                        {% with ff=field|slice:'1:' %}
                                                &nbsp;<i>{% get_verbose_field_name cl.model ff %} (equal)</i><br/>
                                        {% endwith %}
                                {% elif field|slice:':1' == '^' %}
                                        {% with ff=field|slice:'1:' %}
                                                &nbsp;<i>{% get_verbose_field_name cl.model ff %} (starts with)</i><br/>
                                        {% endwith %}
                                {% else %}
                                        {% with ff=field %}
                                                &nbsp;<i>{% get_verbose_field_name cl.model ff %} (contains)</i><br/>
                                        {% endwith %}
                                {% endif %}
                        {% endfor %}
                </span>
# ....
```

**cs_tags** is ...templatetags/cs_tags.py:
```python
from django import template

register = template.Library()

@register.simple_tag
def get_verbose_field_name(instance, field_name):
    """
    Returns verbose_name for a field or field if missing.
    """
    verbose_name = field_name
    try:
        verbose_name = instance._meta.get_field(field_name).verbose_name.title()
    except:
        pass
    return verbose_name
```

**css** (I put the style in base.html)
```css
<style type="text/css">
        .couponcode:hover .coupontooltip {
            display: block;
        }

        .coupontooltip {
            display: none;
            background: #EDEFF1;
            margin-left: 15px;
            padding: 10px;
            margin-top: 10px;
            position: absolute;
            z-index: 1000;
            width: 200px;
            border: 1px solid #DDDDDD;
            border-radius: 10px;
        }
</style>
```
