### ISSUE TITLE
Disabling the action "delete_selected" removes the "Save" button

### ISSUE THREAD

**Issue by bradleyg** [darklow/django-suit#94]
``` python
admin.site.disable_action('delete_selected')
```

This not only removes the "Deleted Selected" action but also removes the "Save" button to the right of it (which is used for inline editables).

I'm currently using this CSS workaround.

``` css
.actions, .action-checkbox, .action-checkbox-column {
    display: none;
}
```

The regular admin doesn't show this behaviour.
